### PR TITLE
change the circleci arrow cache

### PR DESCRIPTION
**Pull request by srsuryadev**
### Summary

Changing the cache version in the circleci config, since we are using the latest arrow release version in the install arrow script now, https://github.com/UWHustle/hustle/blob/master/install_arrow.sh#L5

### CODE REVIEW

**Comment by srsuryadev** [comment]
Hi Prof. Jignesh Patel,

It seems we need to configure the branch protection rules in this new repo so that the build and other checks get triggered before merging.

https://support.circleci.com/hc/en-us/articles/360004346254-Workflow-status-checks-never-completes-because-of-ci-circleci-Waiting-for-status-to-be-reported

I think for permission reasons, we could not see the "Branches" tab in the repository "Settings" page.

Thank you,
Surya

**Comment by johnchronis** [comment]
@srsuryadev I will reconfigure the permissions to make this work properly

**Comment by pateljm** [comment]
@srsuryadev Also sent you an invite on GitHub, an accepting that will give you full Admin privileges to the group account. LMK if I messed up the invite.

**Comment by srsuryadev** [comment]
> @srsuryadev I will reconfigure the permissions to make this work properly



> @srsuryadev Also sent you an invite on GitHub, an accepting that will give you full Admin privileges to the group account. LMK if I messed up the invite.

Cool! Now, I am able to see those tabs. Thank you!

**Comment by srsuryadev** [comment]
@johnchronis / @pateljm  I have made the config changes so that the build is triggered even when the PR is made from a forked repo. Also, resetting the arrow cache in CircleCI gets the build to complete successfully.

@johnchronis  now, it is good to merge.

**Pull request merged**
