### PR TITLE
Add flag to toggle the SSBWorkload to use HashAggregate / normal aggregate

### PR DESCRIPTION
**Pull request by GindaChen**
Related to #58.

**Changes**
- Add a `constexpr int aggregate_type` flag inside the `SSBWorkload` to toggle the aggregate operator.
- Use the `get_agg_op` function to return the proper aggregate operator depending on the `aggregate_type` constant.

@srsuryadev I had a [previous commit](https://github.com/UWHustle/hustle/pull/62/commits/f817735d5f3b15aa8bc6fc47fd498301fad06c58#diff-6e6798c8cca4f0af65f5ef611297d16f9d2bcb4992338257bbd943414d1be45aR37-R55) that use preprocessor to do the job - it just looked uglier... Also, I am a little bit struggled to the factory pattern to generate the proper aggregate operator. Let me know if you have any idea.

### CODE REVIEW

**Comment by srsuryadev** [comment]
I think for the SSB benchmark class it's fine since we have an option to configure the in the AggregateOption class which can be used by the optimizer when needed. (Yeah, we can make it cleaner by having a factory pattern, we can handle in the next PR),

**Review by srsuryadev — APPROVED** [review]

**Comment by srsuryadev** [comment]
were you able to check the performance difference?

**Comment by GindaChen** [comment]
This version of `HashAggregate` is actually around 1-3% slower (on the SSB workload on my machine) than the original aggregate algorithm. I haven't run it on a larger dataset just yet, I would guess the data movement here is the culprit. Shall we wait for the second iteration for the performance report?

**Comment by srsuryadev** [comment]
Yeah, sure, just curious to know. I think you can try in cloudlab machine as there will be noises in local machine.

**Comment by GindaChen** [comment]
Is there a typical machine type we will experiment on?

**Comment by srsuryadev** [comment]
I used to run on this machine, (CPU(s): 40 - Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz, L1d cache: 32K, L1i cache: 32K, L2 cache: 256K, L3 cache: 25600K, main memory around : 158 GB) (I could not remember the exact machine type: I think c220g1). However, it is fine if we could not get the same machine it's fine, since we will be comparing with the base version.

**Pull request merged**
