### PR TITLE
Make sure CircleCI works with new Repo

### PR DESCRIPTION
**Pull request by johnchronis**

### CODE REVIEW

**Comment by johnchronis** [comment]
@NicholasCorrado CircleCI is working now!

There are some code compilation issues, can you take a look?

**Comment by NicholasCorrado** [comment]
Only the readme was updated, and everything was fine in master beforehand, so this is a little odd. My guess is that the cache installation of arrow is out of date. I'm forcing circleci to rebuild everything from scratch now; I'll see if this works.

**Comment by NicholasCorrado** [comment]
@johnchronis I commented out the cache restoration lines in the config file, and the build passed. This cache should be saved. When I uncommented out those lines and tried to build again, it failed. I looked at the build details, and it's restoring a cache from 8/26/2020, which I presume is from the PR I submitted yesterday. Any ideas on why this is happening?

**Comment by johnchronis** [comment]
Thanks Nicholas, I will take a look tonight

**Comment by johnchronis** [comment]
@NicholasCorrado  I cleared the cache and it works now :)

**Comment by srsuryadev** [comment]
deleting this branch as it is successfully merged! :-)

**Pull request merged**
