### PR TITLE
[Easy] code reformat and minor reorganization

### PR DESCRIPTION
**Pull request by srsuryadev**
### Summary
In this pull request, auto-reformat, some manual reorganization, and renaming of modules and filenames in the code to google C++ style (as arrow also following the same style guide).

https://google.github.io/styleguide/cppguide.html

No functional changes.

These changes depend on this pull request  #39 

### Change Details
* Auto reformat of code to google c++ style.
* Renaming of files according to the style guide (.cc, .h, and small cases).
* Added license header - Apache License, Version 2.0 to all the source files.
* Added lint checker files
* Some minor module reorganization

### Tests
Since there are no functional changes, ran the existing unit tests,

ctest --output-on-failure

### CODE REVIEW

**Comment by pateljm** [comment]
Love it and pulling the trigger on merging this. 

Apologies to @NicholasCorrado as it may require retouching #39, but hopefully it is not too onerous.

**Comment by johnchronis** [comment]
CircleCI failed after merging this. @NicholasCorrado @srsuryadev can you take a look? 
Were some of the previous changes overwritten?

**Comment by srsuryadev** [comment]
Hi Yannis,

Yes, I am looking into it! It seems did not overwrite the Circle CI config. However, I could see some problems with the arrow libs based on the build logs. Let me check

**Comment by srsuryadev** [comment]
@johnchronis We have changed the arrow version in the file  install_arrow.sh. As part of the pull request #39, so I think we can try by refreshing the arrow cache again and see. https://github.com/UWHustle/hustle/blob/master/install_arrow.sh#L5

Let me try to refresh it.

**Comment by srsuryadev** [comment]
@johnchronis  created a PR to get the new arrow cache to hold the stable version. #43

**Pull request merged**
